name: vscode-makecode Pre-Release

# Currently only run this pipeline on request 
trigger: none
pr: none

parameters:
- name: nodeVersion
  type: string
  default: '20.x'

extends:
  template: pipeline-template.yml
  parameters:
    nodeVersion: ${{ parameters.nodeVersion }}
    isPreRelease: true
    signType: 'test'
